final Map<String, List<String>> permissionLists = {
  'Dashboard': [],
  'Sales & Invoices': [
    'Create Invoices',
    'Edit Invoices',
    'Delete Invoices',
    'View Invoices',
    'Add Invoice Payment'
        'Create Estimates',
    'Edit Estimates',
    'Add Payment',
    'Process Refund',
    'Delete Estimates',
    'View Estimates',
    'Assigned Discounts',
    'Assigned Invoice Commission',
    'Create no tax invoices',
    "Create Refund Receipts",
    "Edit Refund Receipts",
    "Delete Refund Receipts",
    "View Refund Receipts",
    "Create Credit Notes",
    "Edit Credit Notes",
    "Delete Credit Notes",
    "View Credit Notes",
  ],
  'Create Bookings': [
    'Add Booking',
    'Edit Booking',
    'Delete Booking',
    'View Booking',
    'Add Trucks',
    'Edit Trucks',
    'Delete Trucks',
    'View Trucks',
    'Add Trip Expense',
    'Edit Trip Expense',
    'Delete Trip Expense',
    'View Trip Expense',
  ],
  'Garage Maintenance': [
    'Add Service Type',
    'Edit Service Type',
    'Delete Service Type',
    'View Service Type',
    'Add Maintenance Booking',
    'Edit Maintenance Booking',
    'Delete Maintenance Booking',
    'View Maintenance Booking',
  ],
  'Inventory': [
    'Create Products',
    'Edit Product',
    'Delete Product',
    'View Product',
    'Create Product Category',
    'Edit Product Category',
    'Delete Product Category',
    'View Product Category',
    'Create Sub Category',
    'Edit Sub Category',
    'Delete Sub Category',
    'View Sub Category',
    'Add Brands',
    'Edit Brands',
    'Delete Brands',
    'View Brands',
    'Add Inventory',
    'Edit Inventory',
    'Delete Inventory',
    'View Inventory',
    'Adjust Inventory',
    'Check Inventory Reports',
    'Add Units',
    'Edit Units',
    'Delete Units',
    'View Units',
  ],
  'Assets': [
    'Add Assets',
    'Edit Assets',
    'Delete Assets',
    'View Assets',
    'Add Parent Categories',
    'Edit Parent Categories',
    'Delete Parent Categories',
    'View Parent Categories',
    'Add Categories',
    'Edit Categories',
    'Delete Categories',
    'View Categories',
    'Add Depreciation Methods',
    'Edit Depreciation Methods',
    'Delete Depreciation Methods',
    'View Depreciation Methods',
  ],
  'Estimation': [
    'Create Estimates',
    'Edit Estimates',
    'Delete Estimates',
    'View Estimates',
    'Add Terms & Conditions of Sales',
    'Edit Terms & Conditions of Sales',
    'Delete Terms & Conditions of Sales',
    'View Terms & Conditions of Sales',
    'Add Vendors LOGO',
    'Edit Vendors LOGO',
    'Delete Vendors LOGO',
    'View Vendors LOGO',
  ],
  'Preview Templates': [
    'Create Template Previews',
    'Edit Template Previews',
    // 'Delete Template Previews',
    // 'View Template Previews',
    'Add Default Addresses',
    'Edit Default Addresses',
    'Delete Default Addresses',
    'View Default Addresses',
    'Add Default Bank Details',
    'Edit Default Bank Details',
    'Delete Default Bank Details',
    'View Default Bank Details',
  ],
  'Purchase': [
    'Add Purchase Requisition',
    'Edit Purchase Requisition',
    'Delete Purchase Requisition',
    'View Purchase Requisition',
    'Approved Purchase Requisition',
    'Add Quotation',
    'Edit Quotation',
    'Delete Quotation',
    'View Quotation',
    'Approved Quotation',
    'Add Purchase Order',
    'Edit Purchase Order',
    'Delete Purchase Order',
    'View Purchase Order',
    'Approved Purchase Order',
    'Add GRN',
    'Edit GRN',
    'Delete GRN',
    'View GRN',
    'Approved GRN',
  ],
  'Customers': [
    'Add Customer',
    'Edit Customer',
    'Delete Customer',
    'View Customer',
  ],
  'Designation': [
    'Add Designation',
    'Edit Designation',
    'Delete Designation',
    'View Designation',
  ],
  'People': [
    'Add Vendors',
    'Edit Vendors',
    'Delete Vendors',
    'View Vendors',
    'Add Branches',
    'Edit Branches',
    'Delete Branches',
    'View Branches',
    'Add Roles & Permissions',
    'Edit Roles & Permissions',
    'Delete Roles & Permissions',
    'View Roles & Permissions',
    'Add Employees',
    'Edit Employees',
    'Delete Employees',
    'View Employees',
  ],
  'Allowances': [
    'Add Allowance Category',
    'Edit Allowance Category',
    'Delete Allowance Category',
    'View Allowance Category',
  ],
  'Deduction': [
    'Add Deduction Category',
    'Edit Deduction Category',
    'Delete Deduction Category',
    'View Deduction Category',
    'Add Deduction',
    'Edit Deduction',
    'Delete Deduction',
    'View Deduction',
  ],
  'Leaves': ['Add Leave', 'Edit Leave', 'Delete Leave', 'View Leave'],
  'Heavy Equipment': [
    'Add Heavy Equipment Type',
    'Edit Heavy Equipment Type',
    'Delete Heavy Equipment Type',
    'View Heavy Equipment Type',
  ],
  'Settings': [
    'Add Currency Code',
    'Edit Currency Code',
    'Delete Currency Code',
    'View Currency Code',
    'Add Country',
    'Edit Country',
    'Delete Country',
    'View Country',
    'Add Nationality',
    'Edit Nationality',
    'Delete Nationality',
    'View Nationality',
    'Add Discounts',
    'Edit Discounts',
    'Delete Discounts',
    'View Discounts',
  ],
};
